[book]
authors = ["Keon Kim"]
language = "en"
multilingual = false
src = "src"
title = "Isaac"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/keon/isaac"
edit-url-template = "https://github.com/keon/isaac/edit/main/{path}"
site-url = "/isaac/"

[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0
